test_absolute (__main__.TestExercice) ... FAIL
test_factorial (__main__.TestExercice) ... ok
test_prefixes (__main__.TestExercice) ... ok
test_summation (__main__.TestExercice) ... ok
test_verify_ages (__main__.TestExercice) ... ok

======================================================================
FAIL: test_absolute (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 22, in test_absolute
    'Mauvaise réponse'
AssertionError: Lists differ: [None, 5] != [5, 5]

First differing element 0:
None
5

- [None, 5]
+ [5, 5] : Mauvaise réponse

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=1)
